!INTERFILE  :=
!imaging modality := PT
name of data file := bla.s
originating system := GE Discovery 690
!version of keys := STIR6.0
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
number of radionuclides := 1
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {None}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 4
matrix axis label [4] := segment
!matrix size [4] := 1
matrix axis label [3] := view
!matrix size [3] := 32
matrix axis label [2] := axial coordinate
!matrix size [2] := { 12}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 55
minimum ring difference per segment := { 0}
maximum ring difference per segment := { 0}
Scanner parameters:=
  Scanner type := GE Discovery 690
  Number of rings                          := 12
  Number of detectors per ring             := 64
  Inner ring diameter (cm)                 := 81.02
  Average depth of interaction (cm)        := 0.94
  Distance between rings (cm)              := 1.308
  Default bin size (cm)                    := 0.21306
  View offset (degrees)                    := -5.021
  Maximum number of non-arc-corrected bins := 55
  Default number of arc-corrected bins     := 55
  Energy resolution         := 0
  Reference energy (in keV) := 511
  Maximum number of (unmashed) TOF time bins := 55
  Size of unmashed TOF time bins (ps)        := 89
  TOF timing resolution (ps)                 := 550
  Number of blocks per bucket in transaxial direction         := 2
  Number of blocks per bucket in axial direction              := 4
  Number of crystals per block in axial direction             := 6
  Number of crystals per block in transaxial direction        := 9
  Number of detector layers                                   := 1
  Number of crystals per singles unit in axial direction      := 1
  Number of crystals per singles unit in transaxial direction := 1
  Scanner geometry (BlocksOnCylindrical/Cylindrical/Generic)  := Cylindrical
End scanner parameters:=
number of time frames := 1
start vertical bed position (mm) := 0
start horizontal bed position (mm) := 0
!END OF INTERFILE :=
